# Generated by Django 2.1.3 on 2018-11-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapterorder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='firstchapter_id',
            field=models.IntegerField(default=-1),
        ),
    ]
