# Generated by Django 2.1.3 on 2018-11-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dateposted',
            field=models.DateTimeField(),
        ),
    ]
